spring:
  datasource:
    username: root
    password: your-db-password

  mail:
    host: smtp.example.com
    port: 587
    username: noreply@example.com
    password: your-email-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  token:
    sign-key: change-me-in-local-env

platform:
  frontend-base-url: http://localhost:5173
