spring:
  application:
    name: search-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:nacos:shared-common.yaml?group=NOW_DEMO
      - optional:nacos:${spring.application.name}.yaml?group=NOW_DEMO
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=NOW_DEMO
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: NOW_DEMO
        namespace: ${NACOS_NAMESPACE:dev}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: NOW_DEMO
        namespace: ${NACOS_NAMESPACE:dev}
        file-extension: yaml

server:
  port: ${SERVER_PORT:8084}
